### ISSUE TITLE
Use port 2280 instead of 3000

### ISSUE THREAD

**Issue by osetinsky** [Magicking/supercollider-streaming#2]
Awesome work @Magicking !

FYI, based on the configuration in `docker-compose.yml`, it appears one needs to connect to wetty via port 2280 instead of what is listed in the README (3000):

"Connect to wetty term at http://127.0.0.1:3000/wetty with your browser"

**Comment by Magicking** [comment]
Thanks, the project is still at an early stage and the README is not up to date :(

**Comment by Magicking** [comment]
Commit a6bbb719071ef85246865bf8dd6be83a97ef9a6c fix this.
