### ISSUE TITLE
"Couldn't set real time scheduling priority"

### ISSUE THREAD

**Issue by osetinsky** [Magicking/supercollider-streaming#3]
I'm unable to boot SC once I run scvim on wetty. I think it has something to do with jack config because I'm seeing the following audio related error. Any ideas?

![screen shot 2016-12-30 at 5 18 55 pm](https://cloud.githubusercontent.com/assets/1250151/21573582/2e3e7d3c-ceb4-11e6-9469-6bed63ce024d.png)

**Comment by Magicking** [comment]
I guess something changed from the version 3.8 that was used originally.

TODO: pin supercollider and wetty versions using git submodule for a constant build

Jack is used with have a dummy backend which ffmpeg plug itself to it.

**Comment by osetinsky** [comment]
Awesome, thanks @Magicking ! Anything I can help with? I think this is a useful project.

**Comment by Magicking** [comment]
Pull requests are welcome :) I'm not satisfied with either the structure of the project (based on git HEAD) and the use of Archlinux which add a lot randomess due to the rolling, I consider switching to Alpine

**Comment by Magicking** [comment]
Commit f589652a0dd7a5edbc904b580fd918bea4771cda fix this:
 - Switch from Archlinux to Debian to have not rolling release distribution
 - Recompile ffmpeg inside the docker image (not sure if *really* necessary now but might be in the future), imply a longer and larger build
 - Go to http://127.0.0.1:2280/wetty
 - Listen on http://127.0.0.1:2280/live/sc.m3u8
